name: Ruby tests

on: [push, pull_request]

jobs:
  build:
    name: Ruby tests
    runs-on: ${{ matrix.os }}
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: [2.6, 2.7, 3.0.1, 3.1, 3.2]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-ruby-${{ matrix.ruby }}-gems-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/*.gemspec') }}
          restore-keys: |
            ${{ runner.os }}-ruby-${{ matrix.ruby }}-gems-
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Bundle install
        run: |
          gem install bundler -v 2.1.4
          bundle config path vendor/bundle
          bundle install
      - name: Run tests
        run: bundle exec rake test
